CREATE TABLE IF NOT EXISTS MY_APP_TABLE (
    ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

alter table MY_APP_TABLE rename to App_Table;
